<?php

/**
 * 
 * @package		Vitubo
 * @author		Vitubo Team 
 * @copyright   Vitubo Team
 * @link		http://www.vitubo.com
 * @since		Version 1.0
 * @filesource
 *
 */

 /* * **** TINYMCE CONFIGURE ******** */
define('__TINYMCE_MENUBAR__', 'table format view insert edit tools'); // string ('tools table format view insert edit' | 'false')

$tinymce_plugins = '[
        "responsivefilemanager advlist autolink lists link image charmap print preview anchor",
        "searchreplace visualblocks sourcecode fullscreen",
        "insertdatetime media table contextmenu paste textcolor emoticons"
    ]';
define('__TINYMCE_PLUGINS__', $tinymce_plugins);

$tinymce_toolbar = 'toolbar1: "shortcode sourcecode responsivefilemanager | undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | print preview media | forecolor backcolor emoticons | link image | styleselect | fontselect | fontsizeselect"';
define('__TINYMCE_TOOLBAR__', $tinymce_toolbar);

$tinymce_shortcode_list = <<<TINYMCE
{text: "Grid sample", value: "{html:row}<br>{html:col class=&#34;col-md-4&#34;}<br>sample content<br>{/html:col}<br>{html:col class=&#34;col-md-4&#34;}<br>sample content<br>{/html:col}<br>{html:col class=&#34;col-md-4&#34;}<br>sample content<br>{/html:col}<br>{/html:row}"},
{text: "Awesome Icon sample", value: "{html:i class=&#34;fa fa-adjust&#34;}"},
{text: "Soundclound sample", value: "{soundcloud:audio url=&#34;http://soundcloud.com/futuresounds-bgr/aaliyah-enough-said-feat-drake&#34; comments=&#34;true&#34; auto_play=&#34;false&#34; color=&#34;ff7700&#34; width=&#34;100%&#34; height=&#34;81&#34;}"},
{text: "Youtube sample", value: "{youtube:video id=&#34;6acRHWnfZAE&#34; width=&#34;100%&#34; height=&#34;525&#34;}"},
{text: "Vimeo sample", value: "{vimeo:video id=&#34;91440169&#34; width=&#34;100%&#34; height=&#34;325&#34;}"},
{text: "Livestream sample", value: "{livestream:video acounts='3827561' events='2074586' videos='71902797' width='100%' height='550'}"},
{text: "Google map sample", value: "{google:map address=&#34;Hanoi Vietnam&#34; type=&#34;roadmap&#34; width=&#34;100%&#34; height=&#34;525px&#34; zoom=&#34;8&#34; scrollwheel=&#34;true&#34; scale=&#34;true&#34; zoom_pancontrol=&#34;true&#34;}"},
{text: "Color box sample", value: "{style:colorbox color='red'}<br>{html:h4}<br>Red color box<br>{/html:h4}<br>{html:i class='fa fa-cloud-download fa-2'} {/html:i}<br>{html:p}<br>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua<br>{/html:p}<br>{/style:colorbox}"},
{text: "Border box sample", value: "{borderbox:left}<br>{html:h4}Border left box {/html:h4}<br>{html:p}<br>Et harum quidem rerum facilis est et expedita distinctio lorem ipsum dolor sit amet consectetur adipiscing elit.<br>{/html:p}<br>{/borderbox:left}<br>"},
{text: "Tab sample", value: "{html:tabs value=&#34;Tab1|Tab2|Tab3|Tab4&#34;}<br>{html:tab}<br>Raw denim you probably have not heard of them jean shorts Austin. <br>{/html:tab}<br>{html:tab}<br>Food truck fixie locavore,accusamus mcsweeney marfa nulla single-origin coffee squid.<br>{/html:tab}<br>{html:tab}<br>Etsy mixtape wayfarers, ethical wes anderson tofu before they sold out mcsweeney organiclomo retro fanny pack lo-fi farm-to-table readymade. <br>{/html:tab}<br>{html:tab}<br>Trust fund seitan letterpress, keytar raw denim keffiyeh etsy art party before they sold out master cleanse gluten-free squid scenester freegan cosby sweater. <br>{/html:tab}<br>{/html:tabs}"},
{text: "Accordion sample", value: "{html:accordion}<br>{html:collapse active='true' title = 'Collapsible Group Item #1'}<br>Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid.<br> {/html:collapse}<br>{html:collapse title = 'Collapsible Group Item #2'}<br>Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid.<br>{/html:collapse}<br>{html:collapse title = 'Collapsible Group Item #3'}<br>Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid.<br>{/html:collapse}<br>{html:collapse title = 'Collapsible Group Item #4'}<br>Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid.<br>  {/html:collapse}<br>{html:collapse title = 'Collapsible Group Item #5'}<br>Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid.<br> {/html:collapse}<br>{html:collapse title = 'Collapsible Group Item #6'}<br>Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid.<br> {/html:collapse}<br>{/html:accordion}"},
{text: "Lists sample", value: "{list:ul class='list-unstyled'}<br>{list:li}Lorem ipsum dolor sit amet{/list:li}<br>{list:li}Consectetur adipiscing elit{/list:li}<br>{list:li}Integer molestie lorem at massa{/list:li}<br>{list:li}Nulla volutpat aliquam velit<br>{list:_ul}<br>{list:_li}Lorem ipsum dolor sit amet{/list:_li}<br>{list:_li}Consectetur adipiscing elit{/list:_li}<br>{list:_li}Integer molestie lorem at massa{/list:_li}<br>{/list:_ul}<br>{/list:li}<br>{list:li}Faucibus porta lacus fringilla vel{/list:li}<br>{list:li}Aenean sit amet erat nunc{/list:li}<br>{/list:ul}"},
{text: "Heading sample", value: "{html:h1}h1. Bootstrap heading{/html:h1}<br>{html:h2}h2. Bootstrap heading{/html:h2}<br>{html:h3}h3. Bootstrap heading{/html:h3}<br>{html:h4}h4. Bootstrap heading{/html:h4}<br>{html:h5}h5. Bootstrap heading{/html:h5}<br>{html:h6}h6. Bootstrap heading{/html:h6}<br>"},
{text: "Alerts sample", value: "{html:alert-success}{html:strong}Well done!{/html:strong} You successfully read this important alert message. {/html:alert-success}<br>{html:alert-info} {html:strong}Heads up!{/html:strong} This alert needs your attention, but it's not super important. {/html:alert-info}<br>{html:alert-warning} {html:strong}Warning! {/html:strong} Better check yourself, you're not looking too good. {/html:alert-warning}<br>{html:alert-danger} {html:strong}Oh snap! {/html:strong} Change a few things up and try submitting again. {/html:alert-danger}<br>"},
{text: "Alignment sample", value: "{html:p class=&#34;text-left&#34;}<br>Left aligned text.<br>{/html:p}<br>{html:p class=&#34;text-center&#34;}<br>Center aligned text.<br>{/html:p}<br>{html:p class=&#34;text-right&#34;}<br>Right aligned text.<br>{/html:p}<br>{html:p class=&#34;text-justify&#34;}<br>Justified text.<br>{/html:p}"},
{text: "Tooltip sample", value: " {html:strong data-toggle='tooltip' data-placement=&#34;top&#34; title=&#34;This is tooltip content&#34;}rendered as bold text.{/html:strong}"},
{text: "Popover sample", value: "{html:em data-container=&#34;body&#34; data-toggle=&#34;popover&#34; data-placement=&#34;right&#34; data-content=&#34;Vivamus sagittis lacus vel augue laoreet rutrum faucibus.&#34;}rendered as italicized text.{/html:em}"},
{text: "Abbreviations sample", value: "{html:abbr title=&#34;attribute&#34;}attr{/html:abbr}<br>{html:abbr class=&#34;initialism&#34; title=&#34;HyperText Markup Language&#34;}HTML{/html:abbr}"},
{text: "Blockquotes sample", value: "{html:blockquote}<br>{html:p}Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.{/html:p}<br>{/html:blockquote}<br>{html:blockquote}<br>{html:p}Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.{/html:p}<br>{html:footer}Someone famous in {html:cite title=&#34;Source Title&#34;}Source Title{/html:cite}{/html:footer}<br>{/html:blockquote}<br>{html:blockquote class=&#34;blockquote-reverse&#34;}<br>{html:p}Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.{/html:p}<br>{html:footer}Someone famous in {html:cite title=&#34;Source Title&#34;}Source Title{/html:cite}{/html:footer}<br>{/html:blockquote}"},
{text: "Button sample", value: "{html:button class='btn btn-danger' } danger{/html:button}<br>{html:button class='btn btn-default' } default{/html:button}<br>{html:button class='btn btn-primary' } primary{/html:button}<br>{html:button class='btn btn-success' } success{/html:button}<br>{html:button class='btn btn-info' } info{/html:button}<br>{html:button class='btn btn-warning' }warning{/html:button}<br>{html:button class='btn btn-link' }link{/html:button}"},
{text: "Image sample", value: "{html:row}<br>{html:col class='col-md-3'}<br>{html:img src='media/uploads/images/galleries/Tillington/DSC_8858.jpg' alt='Why do we use it?' width='100%'}<br>{/html:col}<br>{html:col class='col-md-3'}<br>{html:img src='media/uploads/images/galleries/Tillington/DSC_8864.jpg' alt='Where does it come from?' width='100%'}<br>{/html:col}<br>{html:col class='col-md-3'}<br>{html:img src='media/uploads/images/galleries/Tillington/DSC_8929.jpg' alt='The standard chunk of' width='100%'}<br>{/html:col}<br>{html:col class='col-md-3'}<br>{html:img src='media/uploads/images/galleries/Tillington/DSC_8933.jpg' alt='Finibus Bonorum et Malorum' width='100%'}<br>{/html:col}<br>{/html:row}"},
{text: "Social Icons sample", value: "{social:rss url='http://www.vitubo.com'}<br>{social:facebook url='http://www.vitubo.com'}<br>{social:twitter url='http://www.vitubo.com'}<br>{social:vimeo url='http://www.vitubo.com'}<br>{social:googleplus url='http://www.vitubo.com'}<br>{social:pintrest url='http://www.vitubo.com'}<br>{social:linkedin url='http://www.vitubo.com'}<br>{social:dropbox url='http://www.vitubo.com'}<br>{social:picasa url='http://www.vitubo.com'}<br>{social:spotify url='http://www.vitubo.com'}<br>{social:jolicloud url='http://www.vitubo.com'}<br>{social:wordpress url='http://www.vitubo.com'}<br>{social:github url='http://www.vitubo.com'}<br>{social:xing url='http://www.vitubo.com'}"},
{text: "Lastest Tweets sample", value: "{social:tweets twitter='vitubocms' num=3}{/social:tweets}"},
{text: "Breadcrumb sample", value: "{breadcrumb:page}{/breadcrumb:page}"},
{text: "Date sample", value: "{php:datetime}<br>{php:datetime format='l'}<br>{php:datetime format='d/m/Y'}<br>{php:datetime format='Y-m-d H:i:s' timestamp='1403661295'}<br>{php:datetime format='r'}"},
{text: "URL sample", value: "{php:url url='contact-us/demo'}{/php:url}"},
{text: "Rating sample", value: "{pf:rating key='your-key'}"},
{text: "Contact sample", value: "{contactform:display id=537195c27eedc}"},
{text: "Comments sample", value: "{pf:comment key='your-key'}"},
{text: "Get file html sample", value: "{html:get source='app/themes/jupiter/demo/get_html.html'}"},
{text: "Audio player sample", value: "{player:audio width=&#34;auto&#34;<br> src=&#34;http://www.nch.com.au/acm/sample.mp3&#34; title=&#34;Sample MP3&#34;<br>subtitle=&#34;Audio Files&#34;<br>poster=&#34;http://imagebase.net/var/thumbs/People/imagebase20_46.jpg&#34;<br> summary=&#34;Description&#34;}"},
{text: "Video player sample", value: "{player:video loop=&#34;true&#34; src=&#34;http://techslides.com/demos/sample-videos/small.mp4&#34; width=&#34;100%&#34; title=&#34;Sample MP4&#34; subtitle=&#34;Video Files&#34;height=&#34;450&#34;}"},
{text: "Tables sample", value: "{html:table class='table'}{html:tr}{html:th}# {/html:th}{html:th}Column heading {/html:th}{html:th}Column heading {/html:th}{html:th}Column heading {/html:th}{html:th}Column heading {/html:th}{html:th}Action {/html:th}{/html:tr}{html:tr class='info'}{html:td}1 {/html:td}{html:td}Column content {/html:td}{html:td}Column content {/html:td}{html:td}Column content {/html:td}{html:td}Column content {/html:td}{html:td}{html:button class='btn btn-success btn-xs' }Edit {/html:button} {html:i} {html:i}{html:button class='btn btn-danger btn-xs' }Delete {/html:button}{/html:td}{/html:tr}{html:tr class='success'}{html:td}2 {/html:td}{html:td}Column content {/html:td}{html:td}Column content {/html:td}{html:td}Column content {/html:td}{html:td}Column content {/html:td}{html:td}{html:button class='btn btn-success btn-xs' }Edit {/html:button} {html:i} {html:i}{html:button class='btn btn-danger btn-xs' }Delete {/html:button}{/html:td}{/html:tr}{html:tr class='active'}{html:td}3 {/html:td}{html:td}Column content {/html:td}{html:td}Column content {/html:td}{html:td}Column content {/html:td}{html:td}Column content {/html:td}{html:td}{html:button class='btn btn-success btn-xs' }Edit {/html:button} {html:i} {html:i}{html:button class='btn btn-danger btn-xs' }Delete {/html:button}{/html:td}{/html:tr}{html:tr class='warning'}{html:td}4 {/html:td}{html:td}Column content {/html:td}{html:td}Column content {/html:td}{html:td}Column content {/html:td}{html:td}Column content {/html:td}{html:td}{html:button class='btn btn-success btn-xs' }Edit {/html:button} {html:i} {html:i}{html:button class='btn btn-danger btn-xs' }Delete {/html:button}{/html:td}{/html:tr}{html:tr class='danger'}{html:td}5 {/html:td}{html:td}Column content {/html:td}{html:td}Column content {/html:td}{html:td}Column content {/html:td}{html:td}Column content {/html:td}{html:td}{html:button class='btn btn-success btn-xs' }Edit {/html:button} {html:i} {html:i}{html:button class='btn btn-danger btn-xs' }Delete {/html:button}{/html:td}{/html:tr}{html:tr}{html:td}6 {/html:td}{html:td}Column content {/html:td}{html:td}Column content {/html:td}{html:td}Column content {/html:td}{html:td}Column content {/html:td}{html:td}{html:button class='btn btn-success btn-xs' }Edit {/html:button} {html:i} {html:i}{html:button class='btn btn-danger btn-xs' }Delete {/html:button}{/html:td}{/html:tr}{/html:table}"},
{text: "Carousel Slider sample", value: "{html:row}{html:_col class='col-sm-6'}{slider:carousel}{slider:img src='media/uploads/images/galleries/London/DSC_3501.jpg' },{slider:img src='media/uploads/images/galleries/London/DSC_3565.jpg' },{slider:img src='media/uploads/images/galleries/London/DSC_3563.jpg' },{slider:img src='media/uploads/images/galleries/London/DSC_3562.jpg' }{/slider:carousel}{/html:_col}{/html:row}"},
{text: "{html:source}", value: "{html:source} code {/html:source}"},
{text: "{html:script}", value: "{html:script} code {/html:script}"},
{text: "{html:div}", value: "{html:div}{/html:div}"},
{text: "{html:a}", value: "{html:a}{/html:a}"},
{text: "{html:strong}", value: "{html:strong}{/html:strong}"}
TINYMCE;

define('__TINYMCE_SHORTCODE_LIST__', $tinymce_shortcode_list);